/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as PhotosPhotoIdRouteImport } from './photos.$photoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhotoIdRoute = PhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/photos/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photos/$photoId'
  id: '__root__' | '/' | '/photos/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotosPhotoIdRoute: typeof PhotosPhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$photoId': {
      id: '/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof PhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotosPhotoIdRoute: PhotosPhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
